layout_spectrum: 0.7740537051805803
typography_spectrum: 0.10382743709453263
color:
  saturation: 0.07589521124147543
  brandStrength: 0.8130673862328882
  lightness: 0.9011163613583782
  brandColors:
    - '#5A0F39'
    - '#E73E62'
    - '#FF0000'
    - '#EC7C96'
    - '#FF00FF'
  rhythmicContrast: 0.31533500227542355
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0644256-c138-4d82-bfca-0e473169809b.png
name: Community
navigation:
  - name: Contact
    url: 'http://www.cyboolo.com'
    type: external
  - name: twitter
    url: 'https://twitter.com/cyboolo'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Créez, publiez & monétisez'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe41332a-f8ec-4227-91a3-a02a9da51c44.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe41332a-f8ec-4227-91a3-a02a9da51c44.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: En mode ZEN
purpose: []
