layout_spectrum: 0.47489818442861853
typography_spectrum: 0.6586213149715879
color:
  saturation: 0.5428667662311162
  brandStrength: 0.6711070750948817
  lightness: 0.968689316176339
  brandColors:
    - '#5A0F39'
    - '#E73E62'
    - '#FF0000'
    - '#EC7C96'
    - '#FF00FF'
  rhythmicContrast: 0.4791281726974809
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0644256-c138-4d82-bfca-0e473169809b.png
name: Community
navigation:
  - name: Contact
    url: 'http://www.cyboolo.com'
    type: external
  - name: twitter
    url: 'https://twitter.com/cyboolo'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Créez, publiez & monétisez'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/903f53a7-a2a1-43c7-8494-3fb331e94300.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/903f53a7-a2a1-43c7-8494-3fb331e94300.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: cyboolo annule la distance entre votre cerveau et le savoir
purpose: []
