layout_spectrum: 0.2611160871691744
typography_spectrum: 0.3392852952807109
color:
  lightness: 0.5976019181593293
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  saturation: 0.39427661613690307
  brandStrength: 0.6260044971114891
  rhythmicContrast: 0.75918964492987
coverPrefs:
  filter: false
name: cyboolo
analytics: {}
purpose:
  - type: external
    url: 'https://cyboolo.eu.auth0.com/login?client=W1jbxu3C003wehR2kbuCJorz9D23hyEB'
    label: DEMARREZ
  - type: external
    url: 'https://en.cyboolo.io/'
    label: "\uD83C\uDDEC\uD83C\uDDE7 EN"
github: true
description: 'Créez, publiez et monétisez rapidement, simplement... sans savoir coder !'
author:
  name: cyboolo - Tous droits réservés - Mentions Légales
  url: 'https://cyboolo.io/mentions-legales-du-site'
  email: support@cyboolo.com
content: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed33f39d-a503-4359-b755-3584d18c4f80.ico
content_rating:
  adult: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Lancez un site e-commerce de cours en ligne
opengraph: {}
logo: null
url: 'https://cyboolo.io/'
