layout_spectrum: 0.4663384508040946
typography_spectrum: 0.6049915927586763
color:
  saturation: 0.536151250464436
  brandStrength: 0.0032403773402260375
  lightness: 0.7311573124603175
  brandColors:
    - '#5A0F39'
    - '#E73E62'
    - '#FF0000'
    - '#EC7C96'
    - '#FF00FF'
  rhythmicContrast: 0.4765587351610423
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0644256-c138-4d82-bfca-0e473169809b.png
name: Cours en ligne
navigation:
  - name: twitter
    url: 'https://twitter.com/cyboolo'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Créez, publiez & monétisez'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5627d9df-2ead-405b-9abe-4363fd235ad4.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5627d9df-2ead-405b-9abe-4363fd235ad4.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: En mode ZEN
purpose:
  - type: external
    label: Accès à cyboolo
    url: 'https://cyboolo.eu.auth0.com/login?client=W1jbxu3C003wehR2kbuCJorz9D23hyEB'
