layout_spectrum: 0.28637412218994807
typography_spectrum: 0.48161587490036273
color:
  lightness: 0.7734312619020849
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  saturation: 0.3981135517765427
  brandStrength: 0.2985398959673683
  rhythmicContrast: 0.8754120159509712
coverPrefs:
  filter: false
name: cyboolo
analytics: {}
purpose: []
github: true
description: 'Créez, publiez et monétisez rapidement, simplement... sans savoir coder !'
author:
  name: cyboolo - Tous droits réservés - Mentions Légales
  url: 'https://cyboolo.io/mentions-legales-du-site'
  email: support@cyboolo.com
content: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed33f39d-a503-4359-b755-3584d18c4f80.ico
content_rating:
  adult: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Lancez votre site e-commerce de vente de cours en ligne
opengraph: {}
logo: null
url: 'https://cyboolo.io/'
