typography_spectrum: 0.3392852952807109
content_rating:
  adult: false
color:
  lightness: 0.5976019181593293
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  saturation: 0.39427661613690307
  brandStrength: 0.6260044971114891
  rhythmicContrast: 0.75918964492987
github: true
opengraph: {}
layout_spectrum: 0.2611160871691744
analytics:
  twitter: nz0pd
  google: UA-114688656-1
author:
  name: ''
  url: 'https://cyboolo.io/mentions-legales-du-site'
  email: support@cyboolo.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/efff5b60-ae36-48bb-aa91-1660bc60a6d7.png
name: eLearning_services
url: 'https://thegrid.ai/elearning'
navigation:
  - name: ENGLISH VERSION
    url: 'https://en.cyboolo.io'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Plateforme eLearning: Créez. Publiez. Monétisez. REPEAT.'
content: []
coverPrefs:
  filter: false
description: >-
  Lancez votre site rapidement et simplement... sans savoir coder ! Dites adieu
  aux vieux LMS et proposez gratuitement ou à la vente: Formations, MOOCS ou
  Cours en ligne
purpose:
  - type: external
    url: 'https://cyboolo.io'
    label: Join cyboolo
