layout_spectrum: 0.08268060496390456
typography_spectrum: 0.4001225493926703
color:
  saturation: 0.5784780591175808
  brandStrength: 0.2318772033324447
  lightness: 0.3792814011928063
  brandColors:
    - '#FFFFFF'
    - '#717791'
    - '#FF8A65'
    - '#66BB6A'
    - '#C7CAD4'
  rhythmicContrast: 0.8303381756821296
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0644256-c138-4d82-bfca-0e473169809b.png
name: Cours en ligne
navigation:
  - name: twitter
    url: 'https://twitter.com/cyboolo'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: COURS EN LIGNE
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb2025df-43d8-4395-818d-9d3fe9b2c0b9.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb2025df-43d8-4395-818d-9d3fe9b2c0b9.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Créez, publiez & monétisez'
purpose:
  - type: external
    label: Accès à cyboolo
    url: 'https://cyboolo.eu.auth0.com/login?client=W1jbxu3C003wehR2kbuCJorz9D23hyEB'
