layout_spectrum: 0.9083495891735991
typography_spectrum: 0.07015739442568532
color:
  saturation: 1
  brandStrength: 0.42629970197575073
  lightness: 0.9081266583091036
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  rhythmicContrast: 0.09232119719027587
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0644256-c138-4d82-bfca-0e473169809b.png
name: Cours en ligne
navigation:
  - name: twitter
    url: 'https://twitter.com/cyboolo'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: COURS EN LIGNE
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb2025df-43d8-4395-818d-9d3fe9b2c0b9.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb2025df-43d8-4395-818d-9d3fe9b2c0b9.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Créez, publiez & monétisez'
purpose:
  - type: external
    label: Accès à cyboolo
    url: 'https://cyboolo.eu.auth0.com/login?client=W1jbxu3C003wehR2kbuCJorz9D23hyEB'
